### ISSUE TITLE
v0.4 and v0.3 not working with pitest-maven 1.2.2

### ISSUE THREAD

**Issue by vincent-fuchs** [alexvictoor/pitest-cucumber-plugin#15]
Hi,

My build with pitest-maven 1.2.2 is succesful. When I add  

    <dependency>
        <groupId>com.github.alexvictoor</groupId>
        <artifactId>pitest-cucumber-plugin</artifactId>
         <version>0.4</version>
    </dependency>

Then I get below error : 

[WARNING] Error injecting: org.pitest.maven.PitMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: org.pitest.util.StringUtil.isNullOrEmpty(Ljava/lang/String;)Z
  at org.pitest.maven.PitMojo.<init>(Unknown Source)
  while locating org.pitest.maven.PitMojo

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
        at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
        at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:36)
        at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
        at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:543)

**Comment by vincent-fuchs** [comment]
OK, sorry for the basic mistake.. pitest-cucumber-plugin was pulling a previous version of org.pitest pitest, that's why it was failing..

just had to add an exclusion like : 

	<plugin>
		<groupId>org.pitest</groupId>
		<artifactId>pitest-maven</artifactId>
		<version>1.2.2</version>

		<dependencies>
			<dependency>
				<groupId>com.github.alexvictoor</groupId>
				<artifactId>pitest-cucumber-plugin</artifactId>
				<version>0.4</version>
				<exclusions>
					<exclusion>
						<groupId>org.pitest</groupId>
						<artifactId>pitest</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
		</dependencies>

		<executions>
			<execution>
				<id>PIT-analysis</id>
				<goals>
					<goal>mutationCoverage</goal>
				</goals>
			</execution>
		</executions>
	</plugin>
